nelmio_api_doc:
    documentation:
        info:
            title: BileMo API
            description: BileMo
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - Bearer: []
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/docs) # Accepts routes under /api except /api/doc
